# Generated by Django 6.1 on 2026-09-02 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miercoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sabado'), ('domingo', 'Domingo')], max_length=15, verbose_name='Dia de la semana')),
                ('hora_apertura', models.TimeField(verbose_name='Apertura')),
                ('hora_cierre', models.TimeField(verbose_name='Cierre')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_interno', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('capacidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=30, unique=True, verbose_name='Documento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
    ]
