# Generated by Django 6.1 on 2026-09-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='alto',
            field=models.PositiveIntegerField(default=70, verbose_name='Alto'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='ancho',
            field=models.PositiveIntegerField(default=120, verbose_name='Ancho'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='forma',
            field=models.CharField(choices=[('rectangular', 'Rectangular'), ('redonda', 'Redonda')], default='rectangular', max_length=20, verbose_name='Forma'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='x',
            field=models.PositiveIntegerField(default=0, verbose_name='Posición X'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='y',
            field=models.PositiveIntegerField(default=0, verbose_name='Posición Y'),
        ),
    ]
