# Generated by Django 6.1 on 2026-09-10 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesaBloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('expires_at', models.DateTimeField()),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='negocio.mesa')),
            ],
            options={
                'db_table': 'plano_mesa_bloqueo',
                'constraints': [models.UniqueConstraint(fields=('mesa',), name='unique_mesa_bloqueo')],
            },
        ),
    ]
