# Generated by Django 6.1 on 2026-09-02 17:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_invitado', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono_invitado', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_invitado', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('num_personas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('pendiente_confirmacion', 'Pendiente de confirmación'), ('pendiente_revision', 'Pendiente de revisión'), ('confirmada', 'Confirmada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('rechazada', 'Rechazada')], max_length=30)),
                ('notas', models.TextField(blank=True, null=True)),
                ('token_confirmacion', models.CharField(blank=True, max_length=100, null=True)),
                ('expiracion_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='negocio.mesa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
