# Generated by Django 6.1 on 2026-09-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='correo_invitado',
            new_name='correo_cliente',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='telefono_invitado',
            new_name='telefono_cliente',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='usuario',
            new_name='usuario_creador',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nombre_invitado',
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre_cliente',
            field=models.CharField(default='Cliente Antiguo', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente_confirmacion', 'Pendiente de confirmación'), ('pendiente_revision', 'Pendiente de revisión'), ('confirmada', 'Confirmada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('rechazada', 'Rechazada')], default='pendiente_confirmacion', max_length=30),
        ),
    ]
