# Generated by Django 6.1 on 2026-09-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_correo_invitado_reserva_correo_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='nombre_cliente',
            field=models.CharField(default='Cliente', max_length=150),
        ),
    ]
