# Generated by Django 6.1 on 2026-09-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_nombre_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente_confirmacion', 'Pendiente de confirmación'), ('pendiente_revision', 'Pendiente de revisión'), ('activa', 'Activa'), ('confirmada', 'Confirmada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('rechazada', 'Rechazada')], default='pendiente_confirmacion', max_length=30),
        ),
    ]
