# Generated by Django 6.1 on 2026-09-15 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_mesa_alto_mesa_ancho_mesa_forma_mesa_x_mesa_y'),
        ('reservas', '0004_alter_reserva_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('num_personas__gte', 1)), name='num_personas_minimo_uno'),
        ),
    ]
